services:
  codeserver:
    image: lscr.io/linuxserver/code-server:latest
    container_name: codeserver
    restart: unless-stopped
    ports:
      - 8443:8443
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Vancouver
      PASSWORD: "sorendevremote"
    volumes:
      - ./config:/config
      - /home/dietpi/Workspace:/home/coder/project
    networks:
      - web

networks:
  web:
    driver: bridge
    external: true
